/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/expenses` | `/expenses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/expense/new`; params?: Router.UnknownInputParams; } | { pathname: `/expense/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/expense/create/[formId]`, params: Router.UnknownInputParams & { formId: string | number; } } | { pathname: `/expense/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/expenses` | `/expenses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/expense/new`; params?: Router.UnknownOutputParams; } | { pathname: `/expense/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/expense/create/[formId]`, params: Router.UnknownOutputParams & { formId: string; } } | { pathname: `/expense/edit/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/expenses${`?${string}` | `#${string}` | ''}` | `/expenses${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/expense/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/expenses` | `/expenses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/expense/new`; params?: Router.UnknownInputParams; } | `/expense/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/expense/create/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/expense/edit/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/expense/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/expense/create/[formId]`, params: Router.UnknownInputParams & { formId: string | number; } } | { pathname: `/expense/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
